# Generated by Django 3.2.4 on 2021-07-11 23:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('valid', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmaceutical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('generic_name', models.CharField(max_length=200, null=True)),
                ('product_type', models.TextField(choices=[('TABLET', 'Tablet'), ('SYRUP', 'Syrup'), ('Oral Suspension', 'Oral Suspension'), ('IV Infusion', 'IV Infusion'), ('Capsule', 'Capsule'), ('Injection', 'Injection'), ('Powder for Suspension', 'Powder for Suspension'), ('Oral Gel', 'Oral Gel')], null=True)),
                ('price', models.FloatField()),
                ('instock', models.PositiveIntegerField(null=True)),
                ('pharmaceutical_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.pharmaceutical')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('qty', models.IntegerField(default=1)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.product')),
            ],
        ),
    ]
