# Generated by Django 3.2.4 on 2021-07-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid'), ('DRAFT', 'Draft')]),
        ),
    ]
